### PR TITLE
leadership re-write

### LINKED ISSUE #895: Leader failed to validate its own blocks
**Mandatory Information**
1. `jcli 0.5.5 (master-c3f2dcc4+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`
2. `jormungandr 0.5.5 (master-c3f2dcc4+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]`

**To Reproduce**
```
$RUST_BACKTRACE=1 jormungandr --config node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d07
70 --secret node-secret.yaml --log-level debug
```

```
   0: error_chain::backtrace::imp::InternalBacktrace::new
   1: <error_chain::State as core::default::Default>::default
   2: jormungandr::blockchain::chain::Blockchain::post_check_header
   3: futures::future::chain::Chain<A,B,C>::poll
   4: futures::future::chain::Chain<A,B,C>::poll
   5: <futures::future::map::Map<A,F> as futures::future::Future>::poll
   6: futures::task_impl::std::set
   7: std::thread::local::LocalKey<T>::with
   8: futures::future::Future::wait
   9: jormungandr::blockchain::process::handle_input
  10: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
  11: std::panicking::try::do_call
  12: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  13: <futures::future::catch_unwind::CatchUnwind<F> as futures::future::Future>::poll
  14: <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll
  15: futures::task_impl::std::set
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  18: tokio_threadpool::task::Task::run
  19: tokio_threadpool::worker::Worker::run_task
  20: tokio_threadpool::worker::Worker::run
  21: std::thread::local::LocalKey<T>::with
  22: std::thread::local::LocalKey<T>::with
  23: std::thread::local::LocalKey<T>::with
  24: tokio::runtime::threadpool::builder::Builder::build::{{closure}}
  25: std::thread::local::LocalKey<T>::with
  26: std::thread::local::LocalKey<T>::with
  27: std::sys_common::backtrace::__rust_begin_short_backtrace
  28: std::panicking::try::do_call
  29: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  30: core::ops::function::FnOnce::call_once{{vtable.shim}}
  31: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  32: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  33: start_thread
  34: __clone
) } })
thread 'leadership0' panicked at 'Expect the event to not close', src/libcore/option.rs:1166:5
stack backtrace:
   0: backtrace::backtrace::libunwind::trace
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1: backtrace::backtrace::trace_unsynchronized
             at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs
```

### LINKED ISSUE #982: Error: The system just failed to compute an appropriate instant.
I just upgraded to version 6.1 and ran it using the configuration sample provided in https://iohk.zendesk.com/hc/en-us/articles/360036898153:

```
log:
 format: plain
 level: info
 output: stderr
p2p:
 trusted_peers:
   - address: "/ip4/3.115.194.22/tcp/3000"
     id: ed25519_pk1npsal4j9p9nlfs0fsmfjyga9uqk5gcslyuvxy6pexxr0j34j83rsf98wl2
   - address: "/ip4/13.113.10.64/tcp/3000"
     id: ed25519_pk16pw2st5wgx4558c6temj8tzv0pqc37qqjpy53fstdyzwxaypveys3qcpfl
   - address: "/ip4/52.57.214.174/tcp/3000"
     id: ed25519_pk1v4cj0edgmp8f2m5gex85jglrs2ruvu4z7xgy8fvhr0ma2lmyhtyszxtejz
   - address: "/ip4/3.120.96.93/tcp/3000"
     id: ed25519_pk10gmg0zkxpuzkghxc39n3a646pdru6xc24rch987cgw7zq5pmytmszjdmvh
   - address: "/ip4/52.28.134.8/tcp/3000"
     id: ed25519_pk1unu66eej6h6uxv4j4e9crfarnm6jknmtx9eknvq5vzsqpq6a9vxqr78xrw
   - address: "/ip4/13.52.208.132/tcp/3000"
     id: ed25519_pk15ppd5xlg6tylamskqkxh4rzum26w9acph8gzg86w4dd9a88qpjms26g5q9
   - address: "/ip4/54.153.19.202/tcp/3000"
     id: ed25519_pk1j9nj2u0amlg28k27pw24hre0vtyp3ge0xhq6h9mxwqeur48u463s0crpfk
rest:
 listen: 127.0.0.1:3101
storage: "./storage"
```

The node was started with:
```
RUST_BACKTRACE=full ./jormungandr --config ./node-config.yaml --genesis-block-hash adbdd5ede31637f6c9bad5c271eec0bc3d0cb9efb86a5b913bb55cba549d0770
```

As seen below, after a few minutes the node crashed with the following stack trace:

```
Oct 18 18:19:56.453 INFO Starting jormungandr 0.6.1 (HEAD-a0de8d4, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)], task: init
Oct 18 18:19:56.454 WARN Node started without path to the stored secret keys (not a stake pool or a BFT leader), task: init
Oct 18 18:19:56.454 INFO storing blockchain in '"./storage/blocks.sqlite"', task: init
Oct 18 18:19:56.456 INFO connecting to bootstrap peer 3.115.194.22:3000, peer_addr: 3.115.194.22:3000, task: bootstrap
Oct 18 18:44:04.188 INFO switching to new candidate branch, peer_addr: 3.115.194.22:3000, task: bootstrap
Oct 18 18:44:04.196 INFO initial bootstrap completed, peer_addr: 3.115.194.22:3000, task: bootstrap
Oct 18 18:44:04.196 INFO starting task, task: client-query
Oct 18 18:44:04.197 INFO adding P2P Topology module: trusted-peers, task: network
Oct 18 18:44:04.197 INFO connecting to initial gossip peer, peer_addr: 52.57.214.174:3000, task: network
Oct 18 18:44:04.197 INFO connecting to initial gossip peer, peer_addr: 54.153.19.202:3000, task: network
Oct 18 18:44:04.197 INFO connecting to initial gossip peer, peer_addr: 3.115.194.22:3000, task: network
thread 'leadership1' panicked at 'Oct 18 18:44:04.197not yet implemented: The system just failed to compute an appropriate instant.
This could be due to a system suspension or hibernation, in order not to miss out on future
leader elections please prevent your system from suspending or hibernating.
',  jormungandr/src/leadership/mod.rs:183:17
stack backtrace:
CRIT system recorded a 1230s delay. This could be due to a system suspension or hibernation, in order not to miss out on future leader elections please prevent your system from suspending or hibernating., epoch: 237, reason: second time provided was later than self, slot_system_time: 2019-10-18T07:53:34+00:00, now: 2019-10-18T08:14:04.197953472+00:00, task: leadership
Oct 18 18:44:04.198 INFO Starting 1 workers, scope: global
Oct 18 18:44:04.198 INFO connecting to initial gossip peer, peer_addr: 13.52.208.132:3000, task: network
Oct 18 18:44:04.198 INFO Starting server on 127.0.0.1:3101, scope: global
   0:     0x555744694f58 - backtrace::backtrace::libunwind::trace::h89fcc71e59e3bc5b
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/libunwind.rs:88
   1:     0x555744694f58 - backtrace::backtrace::trace_unsynchronized::h0bad9be1379e729a
                               at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.34/src/backtrace/mod.rs:66
   2:     0x555744694f58 - std::sys_common::backtrace::_print::hd3382a1f33c473da
                               at src/libstd/sys_common/backtrace.rs:47
   3:     0x555744694f58 - std::sys_common::backtrace::print::h0ec6f03cfb8e76a6
                               at src/libstd/sys_common/backtrace.rs:36
   4:     0x555744694f58 - std::panicking::default_hook::{{closure}}::h96cbf7b454e3f557
                               at src/libstd/panicking.rs:200
   5:     0x5557446946a7 - std::panicking::default_hook::h95a8f00337383d83
                               at src/libstd/panicking.rs:214
   6:     0x5557446946a7 - std::panicking::rust_panic_with_hook::h92f98b46e22f14ed
                               at src/libstd/panicking.rs:477
   7:     0x5557446941cf - std::panicking::continue_panic_fmt::h25abfbb4e5b7043a
                               at src/libstd/panicking.rs:384
   8:     0x55574469417c - std::panicking::begin_panic_fmt::hc33ce01c7f7cd52d
                               at src/libstd/panicking.rs:339
   9:     0x5557442eed8c - futures::future::chain::Chain<A,B,C>::poll::h27f95323f58f2f6d
  10:     0x555744705b1b - <futures::future::map_err::MapErr<A,F> as futures::future::Future>::poll::h3711bd19806ddeb8
  11:     0x555744689bb0 - futures::task_impl::std::set::he6c155cd71518697
  12:     0x555744685ba9 - tokio_threadpool::worker::Worker::run_task::h1a928c93437110f5
  13:     0x555744685128 - tokio_threadpool::worker::Worker::run::h127f571d23884c72
  14:     0x55574466ad50 - std::thread::local::LocalKey<T>::with::hc02698f8f289735c
  15:     0x55574466ca6c - tokio::runtime::threadpool::builder::Builder::build::{{closure}}::h97052278c7aa38fb
  16:     0x55574468219f - std::sys_common::backtrace::__rust_begin_short_backtrace::h54d02e0626264f8d
  17:     0x5557446835a1 - core::ops::function::FnOnce::call_once{{vtable.shim}}::hf1d4ccfc0e2a8cde
  18:     0x5557446a27ef - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2877b2aefb0fd627
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  19:     0x5557446a3c8c - <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h13f473dbcdaa0fef
                               at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  20:     0x5557446a3c8c - std::sys_common::thread::start_thread::h562a7c4953cb1d31
                               at src/libstd/sys_common/thread.rs:13
  21:     0x5557446a3c8c - std::sys::unix::thread::Thread::new::thread_start::h382c6ae14181d163
                               at src/libstd/sys/unix/thread.rs:79
  22:     0x7f07633894cf - start_thread
  23:     0x7f076329e2d3 - clone
  24:                0x0 - <unknown>
not yet implemented: The system just failed to compute an appropriate instant.
This could be due to a system suspension or hibernation, in order not to miss out on future
leader elections please prevent your system from suspending or hibernating.
```

Notice the computer did not sleep/hibernate. I was using it the whole time.

My details:
```
jcli 0.6.1 (HEAD-a0de8d4, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jormungandr 0.6.1 (HEAD-a0de8d4, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

Running on Manjaro Linux 64bit.
```

### LINKED ISSUE #1024: Invalid block should not unwrap on the chain task and panic
Running latest git master code as of 23 October.

Network of ~10-20 peers was producing new blocks at a rate 1 block every ~5-60 seconds.
I turned off automatic time synchronization in the settings of my Windows laptop while my leader-mode node was running, then adjusted my clock forward by 10 minutes and saved the changes.

Around the next time my leader node produced its next block, sounds like at least a couple of other nodes crashed - also the network seemed to go into the mode where only my node's leader event produced blocks were being propagated throughout... these two events resulted in the gap between next 5-6 blocks going from 5-60 seconds to 1-10 minutes.

Eventually I set my clock back to correct time and restarted my node. Eventually things went back to normal.

### LINKED ISSUE #1065: node panicked - "cannot process leadership block" - cluster with 2 nodes on local pc; v0.7.0-rc4
**Describe the bug**
Node panicked when the second node started to create blocks.

**Mandatory Information**
```
jcli 0.7.0-rc4 (HEAD-56906548, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
jormungandr 0.7.0-rc4 (HEAD-56906548, release, windows [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
```

**To Reproduce**
0. delete the storage files for both nodes
1. start node1 - `jormungandr ---genesis-block block-0.bin --config node_config.yaml --secret node_secret.yaml`
2. start node2 - `jormungandr --config node_config.yaml --secret node_secret.yaml --genesis-block-hash c5a7f2b5832a0e1715880ef2c8eadb2d8e6f0ca2fd60bf83d3aa164539df6da6`
3. send funds from faucet to accout that would delegate to node2 - `bash send-money.sh ca1sku4yc68q9cuwlsg296l6yrk6ccth2pzqu26r4s5r8enymyfeyptgl5vxk4 28000000000000 9001 ed25519e_sk18r7nd20gaxjfgmahyqu2vngv98leqefcdcft2nevcakpf999spx55t4ph8ryqslp6ac7uryekjcqsqzl63rjpmh0k92dvquesweq38cc8a0wc`
4. delegate accout from step 3 to node2's stake pool - `bash delegate-account.sh 223fe74ad117c5a012d4e08eb585803787766f784a3b5addbe0d753d39ab0966 9002 ed25519e_sk1xpdwnr5wx54mh4fpexxsyrc9n0zejfnf7pczr0zr9c3ym98wgpde2drs8t6lkshgeg5z4n2l7lkgkj4kyw97a62mljsrljze9j0c6zgh5j28d`
5. wait for 2 epochs to pass
6. at the begining of the third epoch, node1 is crashing; node2 continues to create blocks

**Expected behavior**
The nodes should not crash and each one should create valid blocks based on the staked percent.

**Additional context**
- cluster of 2 nodes on the same win 10 machine
- node1 acts as faucet; node2 acts as stake pool; both stake pool certificates are set in genesis file at startup
- "consensus_genesis_praos_active_slot_coeff": 1
- "slot_duration": 2
- "slots_per_epoch": 50
- node 1 files
[node1.zip](https://github.com/input-output-hk/jormungandr/files/3801311/node1.zip)
[node1_logs.txt](https://github.com/input-output-hk/jormungandr/files/3801312/node1_logs.txt)
- node 2 files
[node2.zip](https://github.com/input-output-hk/jormungandr/files/3801313/node2.zip)

### PR DESCRIPTION
**Pull request by NicolasDP**
closes #1065 
closes #1024 
closes #895 
closes #982 
baby step for #50 

The main idea is to have a more pro-active approach to the leader election scheduling. Instead of pre-computing the instant the leader election should happen, this is computed every steps against the system clock.

This is, somehow, a come back to the first (and simpler) algorithm: we loop and we compute at every step how long we need to wait until the next event of interest (a slot to create a block or a new epoch and new slots to create the block).

This is still a draft, however it is pretty much stable as it is:

- [x] remove the active wait on a future in the `Module::new` function and instead return a future;
- [x] add more logging for better reporting
- [x] update the leader log status to include the case when an event is rejected
- [x] there are some unwrap that could be removed

### CODE REVIEW

File: jormungandr/src/leadership/process.rs [hunk 1]
```diff
@@ -0,0 +1,630 @@
...
+                "Eek... we missed an event schedule, system time might be off?"
+            );
+
+            let tell_user_about_failure = event_logs
+                .set_status(LeadershipLogStatus::Rejected {
+                    reason: "Missed the deadline to compute the schedule".to_owned(),
+                })
+                .map_err(|()| unreachable!());
+
+            Either::B(Either::B(tell_user_about_failure.map(|()| self)))
```
Comment (mzabaluev) [inline jormungandr/src/leadership/process.rs]: This could be broken up into smaller functions so that there are no nested `Either`s.

File: jormungandr/src/leadership/process.rs [hunk 2]
```diff
@@ -0,0 +1,630 @@
...
+            Either::A(self.action_run_schedule(running_ref, slot_start, nb_slots))
+        } else {
+            // The only reason this would happen is if we had accepted a block
+            // that is set in the future or our system local date time is off
+
+            crit!(
+                logger,
+                "It seems the current epoch tip is way ahead of its time."
+            );
+            Either::B(future::ok(self))
```
Comment (mzabaluev) [inline jormungandr/src/leadership/process.rs]: Is that really an `Ok`? If the node is supposed to go on after this, the log level should not be that severe.

**Comment by rinor** [comment]
Not exactly a technical argument, but still, while testing this branch it *felt* smooth :). Thank you

File: jormungandr/src/leadership/process.rs (hunk 2 above)
Comment (NicolasDP) [reply jormungandr/src/leadership/process.rs]: For now yes. It is critical for the stake pool operation. Not critical for the normal operation of the node.

Comment (NicolasDP) [reply jormungandr/src/leadership/process.rs]: maybe an error then

File: jormungandr/src/leadership/process.rs (hunk 1 above)
Comment (NicolasDP) [reply jormungandr/src/leadership/process.rs]: yes and trying to remove the unwraps in this function too.
