### PR TITLE
network: Rewrite the client state machine

### LINKED ISSUE #923: Suspected file descriptor leak (ERRO Error while accepting connection on 0.0.0.0:3000: Os)
**Describe the bug**
First error in logs are "ERRO Error while accepting connection on 0.0.0.0:3000: Os { code: 24, kind: Other, message: "Too many open files" }, task: network", after a while its starts spamming "ERRO cannot send PullHeaders request to network: send failed because receiver is gone, task: block" and node stops receving blocks

**Mandatory Information**
1. jcli 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]
2. jormungandr 0.5.6 (HEAD-7ab929e+, release, linux [x86_64]) - [rustc 1.38.0 (625451e37 2019-09-23)]

**To Reproduce**
Dont know how to reproduce, happens after the node has run a few hours

**Expected behavior**
No error

**Additional context**
See appendix for output logs and strace logs. I have four examples as I happens every time I try to run my node.

[errPullHeader.zip](https://github.com/input-output-hk/jormungandr/files/3717092/errPullHeader.zip)

### PR DESCRIPTION
**Pull request by mzabaluev**
More disciplined polling loop organization in the form of `ProcessingOutcome` and `Progress`.
Don't spin off separate tasks for processing inbound fragment and gossip streams, as this may cause the background HTTP client to linger after the `Client`'s future has resolved.
Expose the sinks and the gossip processing state in `mod subscription` to enable code reuse in the client.

Might fix #923 and #995.

### CODE REVIEW

File: jormungandr/src/network/subscription.rs [hunk 1]
```diff
@@ -20,136 +19,74 @@ pub fn process_block_announcements<S>(
...
-                core_error::Code::Aborted,
-                "the node stopped processing blocks",
-            )
-        })
-    }
+    let stream = inbound.map_err(move |e| {
+        debug!(
+            stream_err_logger,
+            "block subscription stream failure";
+            "error" => ?e,
```
Comment (NicolasDP) [inline jormungandr/src/network/subscription.rs]:
```suggestion
            "reason" => ?e,
```

just so we remain consistent?

Comment (mzabaluev) [reply jormungandr/src/network/subscription.rs]: That's inconsistent by me :grin: I've been using `"error" => ?e` in debug logs and `"reason" => %e` in info logs which should produce more user-friendly messages.

I think it's time to deliberate and lay down the law on this.
