### PR TITLE
Safeguards against connecting to self

### LINKED ISSUE #1016: Old gossip may cause the node to connect to self
When a node changes its ID and its old ID is still in gossip, it may attempt to connect to itself. We should detect this and quash any such old gossip, too.

Apart from being obviously wrong, it may be a cause of weird `accept` errors on Mac OS (#953).

### PR DESCRIPTION
**Pull request by mzabaluev**
Pending changes in poldercast to not cause the assertion to fail.

Fixes #1016

### CODE REVIEW

File: jormungandr/src/network/mod.rs [hunk 1]
```diff
@@ -352,6 +352,11 @@ fn connect_and_propagate_with<F>(
         }
     };
     let node_id = node.id();
+    assert_ne!(
```
Comment (NicolasDP) [inline jormungandr/src/network/mod.rs]:
```suggestion
    debug_assert_ne!
```

what about a debug assert instead?

and returning early with an error in the log if that is the case? Just would like to avoid crash now on the node for something that we can _work around_ if it happens

Comment (mzabaluev) [reply jormungandr/src/network/mod.rs]: Could do, but this is meant to just double-check after poldercast which should not give us the self node in views. I think I'd try to go in, make a fix in poldercast and update Cargo.toml with the new version for this branch.

Comment (mzabaluev) [reply jormungandr/src/network/mod.rs]: @NicolasDP is already reworking poldercast, replaced this with a warning and an early return until that is done.
