### PR TITLE
explorer: load all available branches during bootstrap

### LINKED ISSUE #2790: Explorer spawned with passive node cannot find transaction
**Describe the bug**
having network topology like below:

image

Where leader3 is a passive node with explorer

I'm sending transaction to node 1, with expectation that explorer setup on passive node would show it when sending query:
```
query:
{
     transaction(id: "bfa87e6841b2fabda40502efebeb129f1b2f09a2ca231193bb129ceb81699595") {
        id
    }
}", against: http://127.0.0.1:8002/explorer/graphql
```

Unfortunately i'm receiving an error:
```
Response: Response { data: None, errors: Some([Error { message: "transaction not found: bfa87e6841b2fabda40502efebeb129f1b2f09a2ca231193bb129ceb81699595", locations: Some([Location { line: 2, column: 5 }]), path: Some([Key("transaction")]), extensions: None }]) }
```
**Mandatory Information**
1. `jcli --full-version` output: `newest master`
2. `jormungandr --full-version` output: `newest master`

**To Reproduce**
`cargo run -- --scenario passive_node_explorer`

**Expected behavior**
transaction should be available in explorer

### PR DESCRIPTION
**Pull request by eugene-babichenko**
resolves #2790

### CODE REVIEW

File: jormungandr/src/explorer/mod.rs [hunk 1]
```diff
@@ -216,13 +216,38 @@ impl ExplorerDB {
...
+                let block = blockchain.storage().get(hash)?.ok_or_else(|| {
+                    Error::from(ErrorKind::BootstrapError(format!(
+                        "couldn't get block {} from the storage",
+                        hash
+                    )))
+                })?;
+                hash = block.header.block_parent_hash();
+                blocks.push(block);
+            }
+            blocks.reverse();
```
Comment (enzoc4) [inline jormungandr/src/explorer/mod.rs:244]: I would use `pop` as this is kind of recursive/stack-like, but probably doesn't make any difference.

File: jormungandr/src/explorer/mod.rs [hunk 2]
```diff
@@ -216,13 +216,38 @@ impl ExplorerDB {
...
                 Ok(db)
             })
-            .await
+            .await?;
+
+        for branch in blockchain.branches().branches().await.iter() {
+            let mut hash = branch.hash();
+            let mut blocks = vec![];
+            loop {
+                if db.get_block(&hash).await.is_some() {
```
Comment (enzoc4) [inline jormungandr/src/explorer/mod.rs:232]: I would just use `apply_block` and see if it returns the `AncestorNotFound` error. Otherwise I would use directly the multiverse lookup, as `get_block` only looks in the current explorer branch (although that will change with #2801), which I think may lead to applying a block twice.

File: jormungandr/src/explorer/mod.rs (hunk 1 above)
Comment (eugene-babichenko) [reply jormungandr/src/explorer/mod.rs:244]: Hm, it actually could make difference. At least this would be a single vector pass instead of two.

File: jormungandr/src/explorer/mod.rs (hunk 2 above)
Comment (eugene-babichenko) [reply jormungandr/src/explorer/mod.rs:232]: > as `get_block` only looks in the current explorer branch

Thanks for noting that. Yeah, for some branching cases this may result into applying a block twice. But will it break anything apart from the performance? Anyway, these branches are rather short (less than 10 blocks) and I wouldn't care much for the performance here. This is a procedure that is ran onle once and we are going to drop it soon.

Comment (enzoc4) [reply jormungandr/src/explorer/mod.rs:232]: Hmm, for some reason I actually thought `apply_block` was going to throw an error, but now I think you are right, it will only affect performance. So yeah, it's fine to leave it as it is I guess.

**Review by enzoc4 — APPROVED** [review]
